---
title: "Research"
---

# Peer Reviewed Publications

1. **Peressotti, Giuseppe** (2025). “Digital Provision Inclusion in Trade Agreements: the Death of (Digital) Distance through a Gravity Model Approach.” *European Journal of International Relations*. (OnlineFirst)

2.  Elmore, Naela, Kashmiri Medhi, **Giuseppe Peressotti**, and Jonathan Pinckney (2025). “Mapping the ROAD to Democracy: A Global Dataset of Overturning Attempts and Organizations in Civil Resistance Transitions.” *Journal of Peace Research*. (Forthcoming)

# Working Papers

1. **Peressotti, Giuseppe**, Huei-Jyun Ye. “Why Take a Detour: The Choice Between Bilateral and Mega-PTAs.”

2. **Peressotti, Giuseppe**. “The Regionalism of Digital Globalization: a Network Analysis of Digital Provisions as part of Preferential Trade Agreements.”

3. **Peressotti, Giuseppe**. “The Impact of Intellectual Property Provisions as Part of PTAs: Can Institutional Quality be a Driver of Innovation?” 

# Work In Progress

1. **Peressotti, Giuseppe**, Ricardo R. Noe. “The Moral Economy of Informality: Trust, Reciprocity, and Entrepreneurial Coordination in Guatemala.” 

2.  Elmore, Naela, **Giuseppe Peressotti**, Maitreyi Pillai, Jonathan Pinckney. “Watch Your Back: Identifying Overturning Organizations in Civil Resistance Transitions.” 

3.  **Peressotti, Giuseppe**, Kelvin Chun Man Chan, Minh Dao, Sadman Shafiq. “The Determinants of Prospective BRICS+ Accession: Toward Institutional Homogeneity?” 